title: Alejandra Lopez # your name (or website title) here
logo: "/images/me.jfif?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I am a graduate student seeking a Masters of Science degree in Geospatial Technologies and looking to transition into a jon in the GIS field.
  I graduated from Texas A&M Univeristy in 2019 with a Bachelor's of Science in GIST and I have ben working in Higher Education since.
  <br><br>
  <a href="https://www.linkedin.com/in/alejandra-lopez-camero/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
