title: Alejandra Lopez # your name (or website title) here
logo: "/images/me.jfif?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I am a graduate student seeking a Masters of Science in Geospatial Technologies and looking to find find a jon in the GIS field.
  I graduated from Texas A&M Univeristy with a Bacherols of Science in GIST and at the moment, I am working as a Financial Aid Advisor at a Private Institution.
  <br><br>
  <a href="https://www.linkedin.com/in/alejandra-lopez-camero/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
